# Generated by Django 4.2.1 on 2023-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('postID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profil_bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
